<h3 class="admin-title">Listado de Banners</h3>
<?php $this->getMesseger(); ?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Banners</h2>
        <a class="btn-admin" title="Nuevo Banner" href="/admin/banner/new">Nuevo Banner</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Descripción</th>
                <th>Imagen</th>
                <th>Posicion</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>