<h3 class="admin-title">Listado de Música</h3>
<?php $this->getMesseger(); ?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Música</h2>
        <a class="btn-admin" title="Nuevo Banner" href="/admin/musica/new">Nueva Música</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Titulo</th>
                <!--<th>Imagen</th>-->
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>