<h3 class="admin-title">Dashboard</h3>
<div class="row-well">
    <p>Bienvenido <?php echo $this->identity->name ?>, Eliga el perfil:</p>
    <ul class="list-opt">

        <li>
            <a target="_blank" href="/preview?perfil=5" title="avanzado"><span class="icad-prom"></span>[avanzado]</a>
        </li>
        <li>
            <a target="_blank" href="/preview?perfil=4" title="basico360"><span class="icad-prom"></span>[basico360]</a>
        </li>
        <li>
            <a target="_blank" href="/preview?perfil=2" title="basico240"><span class="icad-prom"></span>[basico240]</a>
        </li>
        <li>
            <a target="_blank" href="/preview?perfil=2" title="basico128"><span class="icad-prom"></span>[basico128]</a>
        </li>
        <li>
            <a target="_blank" href="/preview?perfil=1" title="basico"><span class="icad-prom"></span>[basico]</a>
        </li>

    </ul>
</div>
