
<div class="row">
    <div class="col-md-12">

      
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-bar-chart-o"></i>
                <h3 class="box-title">Cuadro mensual 2015</h3>
            </div>
            <div class="box-body chart-responsive">
                <div class="chart" id="table_div2" ></div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
   
        
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-bar-chart-o"></i>
                <h3 class="box-title">Visitas Totales de Navegacion</h3>

            </div>
            <div class="box-body chart-responsive">
                <div class="chart" id="visitas_totales_anuales" ></div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-bar-chart-o"></i>
                <h3 class="box-title">Visitas Al Home</h3>
            </div>
            <div class="box-body chart-responsive">
                <div class="chart" id="visitas_home_anuales" ></div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-bar-chart-o"></i>
                <h3 class="box-title">Usuarios Unicos</h3>
            </div>
            <div class="box-body chart-responsive">
                <div class="chart" id="visitas_usuarios_anuales" ></div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col (LEFT) -->
</div>
<br><br>

<script src="<?php echo STATIC_URL ?>css/mobile/css/js/AdminLTE/anual.js" type="text/javascript"></script>
<script src="<?php echo STATIC_URL ?>css/mobile/css/js/AdminLTE/mensual.js" type="text/javascript"></script>