<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header">
                <i class="fa fa-bar-chart-o"></i>
                <h3 class="box-title"><?php echo $this->titulo;  ?></h3>
            </div>
            <div class="box-body chart-responsive">
                <div class="chart" id="table_div2" ></div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col (LEFT) -->
</div><!-- /.row -->
<br><br>
<script src="<?php echo STATIC_URL ?>css/mobile/css/js/jquery.min.js"></script>
<script src="<?php echo STATIC_URL ?>css/mobile/css/js/AdminLTE/semanal.js" type="text/javascript"></script>
