<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>preview/img/basico360/title.jpg">
</div>
<div class="titulo_categoria"><div class="titulo_item_a"><a href="">Correo y Chat</a></div></div>
<div class="item"><div class="titulo_item"> </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="http://www.hotmail.com">Hotmail</a><br/>
        </div>
    </div>
    <div class="item_p_o">
        <div class="text_item">
            <a href="http://www.gmail.com">Gmail</a><br/>
        </div>
    </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="http://www.yahoo.com">Yahoo</a><br/>
        </div>
    </div>
    <div class="text_item_li">
        <a href="/portalwap/redes-sociales">Volver </a>
    </div>
</div>
<div class="verde"></div>
<div class="item_legal">
    <div class="text_item">
        <a href="/portalwap/legal">Legal</a><br/>
    </div>
</div>