
<div class="head">
	<img class="img-head"
             
		src="<?= STATIC_URL?>preview/img/basico360/title.jpg">
</div>
<div class="item"><div class="titulo_item"> </div>
    
    <div id="contenedor"> 
       <div id="destacados">
       <div class="titulo_verde" style="text-align:center">Legal</div>
       <div class="verde"></div>
       <div class="titulo_item" >
        <p>Telefonica Moviles no se hace responsable por la informacion o el contenido de las paginas wap a las que se tendra acceso mediante este medio de telecomunicaciones. La informacion, actualizacion de contenidos y funcionamiento de las referidas paginas wap es responsabilidad de cada titular de las mismas.</p>
                     <p>El costo de la navegación dependerá del plan que usted posee. </p>
                     <p>Si tiene dificultades llame al 104. </p>
       </div>
       <div class="item_legal">
               <div class="text_item">
                   <a href="javascript:history.back(1)">Atrás</a><br/>
               </div> 
       </div>
     </div>
   </div>
</div>




