
<div class="head">
    <img class="img-head"

         src="<?= STATIC_URL ?>preview/img/basico360/title.jpg">
</div>
<div class="item"><div class="titulo_item"> </div>

    <div id="contenedor"> 
        <div id="destacados">
            <div class="titulo_verde" style="text-align:center">Menú interactivo *515#</div>
            <div class="verde"></div>
            <div class="titulo_item" >
                <p>Ahora podrás consultar tu saldo, tarifas, conocer tus promociones, comprar Supercargas y mucho más,
                    a través de un solo número el *515#..</p>
                <p>Marca GRATIS *515# y presiona la tecla "llamar". Apareceré un menú interactivo y podrás:</p>
                <ul><li>
                        Consultar tu saldo.
                    </li>
                    <li>
                        Cancelar supercargas de cobro periodico.
                    </li>
                    <li>
                        Comprar Supercargas de Voz, SMS e Internet.
                    </li>
                    <li>
                        Adquirir Ringtones, Tonos de espera, Dedicatorias, Horóscopo, Chistes y juegos.
                    </li>
                    <li>
                        Comparte tu saldo, Tarifa premiada Llamada por cobrar, SMSxcobrar.
                    </li></ul>
                
                <p>Aprovecha al máximo tu movistar y descubre todo lo que puedes hacer con él. Si tienes un celular postpago, también podrás encontrar en el *515# servicios de música y diversión.</p>
            </div>
            <div class="item_legal">
                <div class="text_item">
                    <a href="javascript:history.back(1)" style="color: white">Atrás</a><br/>
                </div> 
            </div>
        </div>
    </div>
</div>




