<div id="contenedor"> 
    <div class="titulo_categoria"><div class="titulo_item_a"><a href="">Activa tu tono de espera</a></div></div>
    <div class="item"><div class="titulo_item"> </div>
    </div>
    <div class="verde"></div>
    <div id="publicidad">
        <a href="tel:*8889"><img src="<?= STATIC_URL?>preview/img/avanzado//banner_4.gif" width="100%" /></a><br/>
    </div>
    <div class="item_legal">
        <div class="text_item">
            <a href="/portalwap/legal">Legal</a><br/>
        </div>
    </div>
</div>