<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>preview/img/basico360/title.jpg">
</div>
<div class="titulo_categoria"><div class="titulo_item_a"><a href="">Redes Sociales</a></div></div>
<div class="item"><div class="titulo_item"> </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="https://m.facebook.com/">Facebook</a><br/>
        </div>
    </div>
    <div class="item_i_o">
        <div class="text_item">
            <a href="/go?link=https://mobile.twitter.com/">Twitter</a><br/>
        </div>
    </div>
    <div class="item_p_o">
        <div class="text_item">
            <a href="https://www.google.com.pe">Google</a><br/>
        </div>
    </div>	
    <div class="item_p_o">
        <div class="text_item">
            <a href="/portalwap/correo-chat">Correo y chat</a><br/>
        </div>
    </div>	
    <div class="text_item_li">
        <a href="/portalwap">Volver </a>
    </div>
</div>
<div class="verde"></div>
<div class="item_legal">
    <div class="text_item">
        <a href="portalwap/legal">Legal</a><br/>
    </div>
</div>