<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>preview/img/basico360/title.jpg">
</div>
<!--<div class="titulo_categoria">
    <div class="titulo_item_a">
        <a href="">Correo y Chat</a>
    </div>
</div>-->
<section id="examples">
    <section id="vertical">

        <form action="/preview/" method="POST">
            <h1>Movistar Más</h1>
            <p>
                Registrate en el portal, llena tu perfil y en poco tiempo empezarás a recibir ofertas exclusivas de entretenimiento, servicios y mucho más
            </p>
            <?php $this->getMesseger(); ?>
            <fieldset>
                <div class="row">
                    <div class="col-s-6">
                        <label for="input1">Nombre </label>
                        <input type="text" name="nombre" id="input1" placeholder="Nombres" value="">
                        <label for="input1">Apellidos </label>
                        <input type="text" name="apellido" id="input1" placeholder="Apellidos" value=""> 
                        <label for="input1">DNI </label>
                        <input type="text" name="dni" id="input1" placeholder="dni" value=""> 
                        <label for="input-email1">Correo Electronico</label>
                        <input type="text" name="correo"   placeholder="correo" value="">

                        <div class="verde"></div>
                        <label for="check1"><input type="checkbox" name="opt" id="check1" value="si">Acepto recibir ofertas personalizadas en el móvil de Movistar y sus partners</label>
                        <div class="verde"></div>
                        <label for="check2"><input type="checkbox" name="prd" id="check2" value="si">Acepto la política de Protección de Datos</label>

                        <label for="input-date1">Fecha de Nacimiento (dd-mm-aaaa)</label>
                        <input style=" width: 30%;float:left; margin-right: 2%"    type="text" name="dia"  placeholder="DD" value=""> 
                        <input style="width: 30%;float:left;margin-right: 2%"  type="text" name="mes"  placeholder="MM" value=""> 
                        <input style="width: 30%"  type="text" name="anio"  placeholder="AAAA" value=""> 
                        <!--<input type="date" name="fecha_nacimiento" placeholder="dd/mm/aaaa" id="input-date1">-->
                        <label for="select-default1">Sexo</label>
                        <select id="select-default1" name="sexo">
                            <option value='Masculino'>Masculino</option>
                            <option value='Femenino'>Femenino</option>
                        </select>
                    </div>
                    <div class="col-s-6">
                        <label for="select-default1">Provincia</label>
                        <select id="select-default1" name="provincia">
                            <option value='0'>Selecciona Opci&oacute;n...</option> 
                            <option value='Amazonas'>Amazonas</option>
                            <option value='Ancash'>Ancash</option>
                            <option value='Apurimac'>Apurimac</option>
                            <option value='Arequipa'>Arequipa</option>
                            <option value='Ayacucho'>Ayacucho</option>
                            <option value='Cajamarca'>Cajamarca</option>
                            <option value='Callao'>Callao</option>
                            <option value='Cusco'>Cusco</option>
                            <option value='Huancavelica'>Huancavelica</option>
                            <option value='Huanuco'>Huanuco</option>
                            <option value='Ica'>Ica</option>
                            <option value='Junin'>Junin</option>
                            <option value='La Libertad'>La Libertad</option>
                            <option value='Lambayeque'>Lambayeque</option>
                            <option value='Lima'>Lima</option>
                            <option value='Loreto'>Loreto</option>
                            <option value='Madre De Dios'>Madre De Dios</option>
                            <option value='Moquegua'>Moquegua</option>
                            <option value='Pasco'>Pasco</option>
                            <option value='Piura'>Piura</option>
                            <option value='Puno'>Puno</option>
                            <option value='San Martin'>San Martin</option>
                            <option value='Tacna'>Tacna</option>
                            <option value='Tumbes'>Tumbes</option>
                            <option value='Ucayali'>Ucayali</option>
                        </select>

                        <label for="select-default1">Estado Civil</label>
                        <select id="select-default1" name="estado_civil">
                            <option value='0'>Selecciona Opci&oacute;n...</option>
                            <option value='Soltero'>Soltero/a</option>
                            <option value='Casado'>Casado/a</option>
                            <option value='Divorciado'>Divorciado/a</option>
                            <option value='Viudo'>Viudo/a</option>
                            <option value='Conviviente'>Conviviente/a</option>
                        </select>
                        <label for="select-default1">Nivel Educativo</label>
                        <select id="select-default1" name="nivel_educacion">
                            <option value='0'>Selecciona Opci&oacute;n...</option>
                            <option value='Primaria'>Primaria</option>
                            <option value='Secundaria'>Secundaria</option>
                            <option value='Superior'>Superior </option>
                            <option value='MBA/postgrado'>MBA/postgrado</option>
                            <option value='Doctorado'>Doctorado</option>
                        </select>
                        <label for="select-default1">Profesión</label>
                        <select id="select-default1" name="profesion">
                            <option value='0'>Selecciona Opci&oacute;n...</option>
                            <option value='Administracion e Ing Industrial'>Administracion e Ing Industrial</option>
                            <option value='Ama de casa'>Ama de casa</option>
                            <option value='Arquitectura'>Arquitectura</option>
                            <option value='Comunicaciones'>Comunicaciones</option>
                            <option value='Comunicacion Social'>Comunicacion Social</option>
                            <option value='Ingenieria Informatica y Computacion'>Ingenieria Informatica y Computacion</option>
                            <option value='Ingenieria Civil'>Ingenieria Civil</option>
                            <option value='Contabilidad'>Contabilidad</option>
                            <option value='Derecho'>Derecho</option>
                            <option value='Diseno'>Diseno</option>
                            <option value='Economia'>Economia</option>
                            <option value='Educacion'>Educacion</option>
                            <option value='Fotografia'>Fotografia</option>
                            <option value='Gastronomia'>Gastronomia</option>
                            <option value='Ingenieria Mecanica'>Ingenieria Mecanica</option>
                            <option value='Marketing'>Marketing</option>
                            <option value='Medicina'>Medicina</option>
                            <option value='Negocios Internacionales'>Negocios Internacionales</option>
                            <option value='Organizaciones sin fines de lucro'>Organizaciones sin fines de lucro</option>
                            <option value='Psicologia'>Psicologia</option>
                            <option value='Secretariado'>Secretariado</option>
                            <option value='Telecomunicaciones'>Telecomunicaciones</option>
                            <option value='Turismo y Hoteleria'>Turismo y Hoteleria</option>
                            <option value='Ventas y Publicidad'>Ventas y Publicidad</option>
                            <option value='Veterinaria'>Veterinaria</option>
                            <option value='Otros '>Otros </option>
                        </select>

                        <label for="select-default1">Áreas de interés</label>

                       
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Bebes</label>
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Actividades Culturales</label>
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Electrónica</label>
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Salud</label>
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Mascotas</label>
                            <label for="check1"><input type="checkbox" name="area_interes[]" id="check1" value="">Deportes</label>
                        
                        <div class="verde"></div>
                        <label for="check1"><input type="checkbox" name="optlocalizacion" id="check1" value="si">Autorizo a Movistar a enviarme ofertas personalizadas de acuerdo a mi ubicación</label>
                    </div>
                </div>
            </fieldset>
            <div class="form-actions">
                <button type="submit">Guardar</button>
            </div>
        </form>
    </section>
</section>
<div class="verde"></div>
<div class="text_item_li">
    <a href="/preview">Volver </a>
</div>
<div class="verde"></div>
<div class="item_legal">
    <div class="text_item">
        <a href="/preview/servicios/legal">Legal</a><br/>
    </div>
</div>
<style>

    /* *{
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }*/
    form {
        padding: 10px 10%;
    }

    article,
    aside,
    details,
    figcaption,
    figure,
    hgroup,
    main,
    menu,
    nav,
    section,
    summary {
        display: block; }

    audio,
    canvas,
    progress,
    video {
        display: inline-block;
        vertical-align: baseline; }

    audio:not([controls]) {
        display: none;
        height: 0; }

    [hidden],
    template {
        display: none; }

    a {
        background-color: transparent; }

    a:active,
    a:hover {
        outline: 0; }

    abbr[title] {
        border-bottom: 1px dotted; }

    b,
    strong {
        font-weight: bold; }

    dfn {
        font-style: italic; }

    mark {
        background: #ff0;
        color: #000; }

    small {
        font-size: 80%; }

    sub,
    sup {
        font-size: 75%;
        line-height: 0;
        position: relative;
        vertical-align: baseline; }

    sup {
        top: -0.375rem; }

    sub {
        bottom: -0.1875rem; }


    svg:not(:root) {
        overflow: hidden; }

    figure {
        margin: 1rem 2.5rem; }

    button,
    input,
    optgroup,
    select,
    textarea {
        color: inherit;
        font: inherit;
        margin: 0; }

    button {
        overflow: visible; }

    button,
    select {
        text-transform: none; }

    button,
    html input[type="button"],
    input[type="reset"],
    input[type="submit"] {
        -webkit-appearance: button;
        cursor: pointer; }

    button::-moz-focus-inner,
    input::-moz-focus-inner {
        border: 0;
        padding: 0; }

    input[type="number"]::-webkit-inner-spin-button,
    input[type="number"]::-webkit-outer-spin-button {
        height: auto; }

    input[type="search"]::-webkit-search-cancel-button,
    input[type="search"]::-webkit-search-decoration {
        -webkit-appearance: none; }

    fieldset {
        border: 1px solid #c0c0c0;
        margin: 0 2px;
        padding: 0.35rem 0.625rem 0.75rem; }

    legend {
        border: 0;
        padding: 0; }

    textarea {
        overflow: auto; }

    optgroup {
        font-weight: bold; }

    table {
        border-collapse: collapse;
        border-spacing: 0; }

    form {
        -webkit-overflow-scrolling: touch;
        font-size: 100%;
        line-height: 1.4;
        box-sizing: border-box; }

    *, :before, :after {
        box-sizing: inherit; }

    :focus {
        outline: #4d90fe;
        outline-style: solid;
        outline-width: 1px;
        outline-offset: -1px; }

    [tabindex="-1"]:focus {
        outline: none !important; }

    _::-ms-reveal,
    div:not([tabindex]):focus {
        outline: none !important; }

    h1, h2, h3, h4, h5, h6 {
        text-rendering: optimizeLegibility;
        page-break-after: avoid; }

    h1 {
        font-size: 2rem;
        margin: 1.34rem 0; }

    h2 {
        font-size: 1.5rem;
        margin: 1.245rem 0; }

    h3 {
        font-size: 1.17rem;
        margin: 1.17rem 0; }

    h4 {
        font-size: 1rem;
        margin: 1.33rem 0; }

    h5 {
        font-size: 0.83rem;
        margin: 1.386rem 0; }

    h6 {
        font-size: 0.67rem;
        margin: 1.561rem 0; }

    ::-moz-selection {
        background: #b3d4fc;
        text-shadow: none; }

    ::selection {
        background: #b3d4fc;
        text-shadow: none; }

    hr {
        display: block;
        height: 1px;
        border: 0;
        border-top: 1px solid silver;
        margin: 1rem 0;
        padding: 0; }

    abbr {
        cursor: help; }

    .container, .modal-ajax.container,
    .modal-iframe,
    .container-full {
        margin: 0 auto; }
    .container.fixed,
    .fixed.modal-iframe, .fixed .container,
    .fixed .modal-iframe,
    .container-full.fixed, .fixed
    .container-full {
        width: 100%; }

    .container-full {
        overflow-x: hidden; }

    .container, .modal-ajax.container,
    .modal-iframe {
        max-width: 1140px;
        width: calc(100% - 16px); }
    .container.fixed,
    .fixed.modal-iframe, .fixed .container,
    .fixed .modal-iframe {
        width: 1140px; }

    .row,
    [class*="block-row-"] {
        margin: 0 -8px; }

    .no-gutter {
        margin: 0; }

    [class*="block-row-"] {
        display: block;
        padding: 0;
        list-style: none; }

    [class*=col-],
    [class*="block-row-"] > * {
        display: block;
        float: left;
        min-height: 1px;
        width: 100%;
        border-left: 8px solid transparent;
        border-right: 8px solid transparent;
        background-clip: padding-box; }
    [dir="rtl"] [class*=col-], [dir="rtl"]
    [class*="block-row-"] > * {
        float: right; }

    [class*=col-][class*=offset], [class*=col-][class*=push], [class*=col-][class*=pull] {
        position: relative; }

    [class*="block-row-"].no-gutter > *,
    .no-gutter > [class*=col-] {
        border: none;
        background-clip: border-box; }

    .equal-height {
        display: table;
        table-layout: fixed;
        height: 1px;
        width: calc(100% + 16px); }
    .equal-height.no-gutter {
        width: 100%; }
    .equal-height:before {
        display: none !important; }

    .equal-height > [class*=col-] {
        float: none;
        vertical-align: top; }

    .col-xxs-1 {
        width: 8.3333%; }

    .offset-xxs-1,
    .push-xxs-1 {
        left: 8.3333%; }
    [dir="rtl"] .offset-xxs-1, [dir="rtl"]
    .push-xxs-1 {
        left: auto;
        right: 8.3333%; }

    .pull-xxs-1 {
        right: 8.3333%; }
    [dir="rtl"] .pull-xxs-1 {
        right: auto;
        left: 8.3333%; }

    .col-xxs-2 {
        width: 16.6667%; }

    .offset-xxs-2,
    .push-xxs-2 {
        left: 16.6667%; }
    [dir="rtl"] .offset-xxs-2, [dir="rtl"]
    .push-xxs-2 {
        left: auto;
        right: 16.6667%; }

    .pull-xxs-2 {
        right: 16.6667%; }
    [dir="rtl"] .pull-xxs-2 {
        right: auto;
        left: 16.6667%; }

    .col-xxs-3 {
        width: 25%; }

    .offset-xxs-3,
    .push-xxs-3 {
        left: 25%; }
    [dir="rtl"] .offset-xxs-3, [dir="rtl"]
    .push-xxs-3 {
        left: auto;
        right: 25%; }

    .pull-xxs-3 {
        right: 25%; }
    [dir="rtl"] .pull-xxs-3 {
        right: auto;
        left: 25%; }

    .col-xxs-4 {
        width: 33.3333%; }

    .offset-xxs-4,
    .push-xxs-4 {
        left: 33.3333%; }
    [dir="rtl"] .offset-xxs-4, [dir="rtl"]
    .push-xxs-4 {
        left: auto;
        right: 33.3333%; }

    .pull-xxs-4 {
        right: 33.3333%; }
    [dir="rtl"] .pull-xxs-4 {
        right: auto;
        left: 33.3333%; }

    .col-xxs-5 {
        width: 41.6667%; }

    .offset-xxs-5,
    .push-xxs-5 {
        left: 41.6667%; }
    [dir="rtl"] .offset-xxs-5, [dir="rtl"]
    .push-xxs-5 {
        left: auto;
        right: 41.6667%; }

    .pull-xxs-5 {
        right: 41.6667%; }
    [dir="rtl"] .pull-xxs-5 {
        right: auto;
        left: 41.6667%; }

    .col-xxs-6 {
        width: 50%; }

    .offset-xxs-6,
    .push-xxs-6 {
        left: 50%; }
    [dir="rtl"] .offset-xxs-6, [dir="rtl"]
    .push-xxs-6 {
        left: auto;
        right: 50%; }

    .pull-xxs-6 {
        right: 50%; }
    [dir="rtl"] .pull-xxs-6 {
        right: auto;
        left: 50%; }

    .col-xxs-7 {
        width: 58.3333%; }

    .offset-xxs-7,
    .push-xxs-7 {
        left: 58.3333%; }
    [dir="rtl"] .offset-xxs-7, [dir="rtl"]
    .push-xxs-7 {
        left: auto;
        right: 58.3333%; }

    .pull-xxs-7 {
        right: 58.3333%; }
    [dir="rtl"] .pull-xxs-7 {
        right: auto;
        left: 58.3333%; }

    .col-xxs-8 {
        width: 66.6667%; }

    .offset-xxs-8,
    .push-xxs-8 {
        left: 66.6667%; }
    [dir="rtl"] .offset-xxs-8, [dir="rtl"]
    .push-xxs-8 {
        left: auto;
        right: 66.6667%; }

    .pull-xxs-8 {
        right: 66.6667%; }
    [dir="rtl"] .pull-xxs-8 {
        right: auto;
        left: 66.6667%; }

    .col-xxs-9 {
        width: 75%; }

    .offset-xxs-9,
    .push-xxs-9 {
        left: 75%; }
    [dir="rtl"] .offset-xxs-9, [dir="rtl"]
    .push-xxs-9 {
        left: auto;
        right: 75%; }

    .pull-xxs-9 {
        right: 75%; }
    [dir="rtl"] .pull-xxs-9 {
        right: auto;
        left: 75%; }

    .col-xxs-10 {
        width: 83.3333%; }

    .offset-xxs-10,
    .push-xxs-10 {
        left: 83.3333%; }
    [dir="rtl"] .offset-xxs-10, [dir="rtl"]
    .push-xxs-10 {
        left: auto;
        right: 83.3333%; }

    .pull-xxs-10 {
        right: 83.3333%; }
    [dir="rtl"] .pull-xxs-10 {
        right: auto;
        left: 83.3333%; }

    .col-xxs-11 {
        width: 91.6667%; }

    .offset-xxs-11,
    .push-xxs-11 {
        left: 91.6667%; }
    [dir="rtl"] .offset-xxs-11, [dir="rtl"]
    .push-xxs-11 {
        left: auto;
        right: 91.6667%; }

    .pull-xxs-11 {
        right: 91.6667%; }
    [dir="rtl"] .pull-xxs-11 {
        right: auto;
        left: 91.6667%; }

    .col-xxs-12 {
        width: 100%; }

    .offset-xxs-12,
    .push-xxs-12 {
        left: 100%; }
    [dir="rtl"] .offset-xxs-12, [dir="rtl"]
    .push-xxs-12 {
        left: auto;
        right: 100%; }

    .pull-xxs-12 {
        right: 100%; }
    [dir="rtl"] .pull-xxs-12 {
        right: auto;
        left: 100%; }

    .equal-height > [class*=col-xxs] {
        display: table-cell;
        height: 100%; }

    .equal-height > .col-xxs-13 {
        display: table-caption; }

    .block-row-xxs-1 > * {
        width: 100%; }
    .block-row-xxs-1 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-1 > :nth-of-type(1n+1) {
        clear: both; }

    .block-row-xxs-2 > * {
        width: 50%; }
    .block-row-xxs-2 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-2 > :nth-of-type(2n+1) {
        clear: both; }

    .block-row-xxs-3 > * {
        width: 33.3333%; }
    .block-row-xxs-3 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-3 > :nth-of-type(3n+1) {
        clear: both; }

    .block-row-xxs-4 > * {
        width: 25%; }
    .block-row-xxs-4 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-4 > :nth-of-type(4n+1) {
        clear: both; }

    .block-row-xxs-5 > * {
        width: 20%; }
    .block-row-xxs-5 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-5 > :nth-of-type(5n+1) {
        clear: both; }

    .block-row-xxs-6 > * {
        width: 16.6667%; }
    .block-row-xxs-6 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-6 > :nth-of-type(6n+1) {
        clear: both; }

    .block-row-xxs-7 > * {
        width: 14.2857%; }
    .block-row-xxs-7 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-7 > :nth-of-type(7n+1) {
        clear: both; }

    .block-row-xxs-8 > * {
        width: 12.5%; }
    .block-row-xxs-8 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-8 > :nth-of-type(8n+1) {
        clear: both; }

    .block-row-xxs-9 > * {
        width: 11.1111%; }
    .block-row-xxs-9 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-9 > :nth-of-type(9n+1) {
        clear: both; }

    .block-row-xxs-10 > * {
        width: 10%; }
    .block-row-xxs-10 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-10 > :nth-of-type(10n+1) {
        clear: both; }

    .block-row-xxs-11 > * {
        width: 9.0909%; }
    .block-row-xxs-11 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-11 > :nth-of-type(11n+1) {
        clear: both; }

    .block-row-xxs-12 > * {
        width: 8.3333%; }
    .block-row-xxs-12 > :nth-of-type(n+1) {
        clear: none; }
    .block-row-xxs-12 > :nth-of-type(12n+1) {
        clear: both; }

    @media print and (min-width: 536px), screen and (min-width: 37.5em) {
        .col-xs-1 {
            width: 8.3333%; }

        .offset-xs-1,
        .push-xs-1 {
            left: 8.3333%; }
        [dir="rtl"] .offset-xs-1, [dir="rtl"]
        .push-xs-1 {
            left: auto;
            right: 8.3333%; }

        .pull-xs-1 {
            right: 8.3333%; }
        [dir="rtl"] .pull-xs-1 {
            right: auto;
            left: 8.3333%; }

        .col-xs-2 {
            width: 16.6667%; }

        .offset-xs-2,
        .push-xs-2 {
            left: 16.6667%; }
        [dir="rtl"] .offset-xs-2, [dir="rtl"]
        .push-xs-2 {
            left: auto;
            right: 16.6667%; }

        .pull-xs-2 {
            right: 16.6667%; }
        [dir="rtl"] .pull-xs-2 {
            right: auto;
            left: 16.6667%; }

        .col-xs-3 {
            width: 25%; }

        .offset-xs-3,
        .push-xs-3 {
            left: 25%; }
        [dir="rtl"] .offset-xs-3, [dir="rtl"]
        .push-xs-3 {
            left: auto;
            right: 25%; }

        .pull-xs-3 {
            right: 25%; }
        [dir="rtl"] .pull-xs-3 {
            right: auto;
            left: 25%; }

        .col-xs-4 {
            width: 33.3333%; }

        .offset-xs-4,
        .push-xs-4 {
            left: 33.3333%; }
        [dir="rtl"] .offset-xs-4, [dir="rtl"]
        .push-xs-4 {
            left: auto;
            right: 33.3333%; }

        .pull-xs-4 {
            right: 33.3333%; }
        [dir="rtl"] .pull-xs-4 {
            right: auto;
            left: 33.3333%; }

        .col-xs-5 {
            width: 41.6667%; }

        .offset-xs-5,
        .push-xs-5 {
            left: 41.6667%; }
        [dir="rtl"] .offset-xs-5, [dir="rtl"]
        .push-xs-5 {
            left: auto;
            right: 41.6667%; }

        .pull-xs-5 {
            right: 41.6667%; }
        [dir="rtl"] .pull-xs-5 {
            right: auto;
            left: 41.6667%; }

        .col-xs-6 {
            width: 50%; }

        .offset-xs-6,
        .push-xs-6 {
            left: 50%; }
        [dir="rtl"] .offset-xs-6, [dir="rtl"]
        .push-xs-6 {
            left: auto;
            right: 50%; }

        .pull-xs-6 {
            right: 50%; }
        [dir="rtl"] .pull-xs-6 {
            right: auto;
            left: 50%; }

        .col-xs-7 {
            width: 58.3333%; }

        .offset-xs-7,
        .push-xs-7 {
            left: 58.3333%; }
        [dir="rtl"] .offset-xs-7, [dir="rtl"]
        .push-xs-7 {
            left: auto;
            right: 58.3333%; }

        .pull-xs-7 {
            right: 58.3333%; }
        [dir="rtl"] .pull-xs-7 {
            right: auto;
            left: 58.3333%; }

        .col-xs-8 {
            width: 66.6667%; }

        .offset-xs-8,
        .push-xs-8 {
            left: 66.6667%; }
        [dir="rtl"] .offset-xs-8, [dir="rtl"]
        .push-xs-8 {
            left: auto;
            right: 66.6667%; }

        .pull-xs-8 {
            right: 66.6667%; }
        [dir="rtl"] .pull-xs-8 {
            right: auto;
            left: 66.6667%; }

        .col-xs-9 {
            width: 75%; }

        .offset-xs-9,
        .push-xs-9 {
            left: 75%; }
        [dir="rtl"] .offset-xs-9, [dir="rtl"]
        .push-xs-9 {
            left: auto;
            right: 75%; }

        .pull-xs-9 {
            right: 75%; }
        [dir="rtl"] .pull-xs-9 {
            right: auto;
            left: 75%; }

        .col-xs-10 {
            width: 83.3333%; }

        .offset-xs-10,
        .push-xs-10 {
            left: 83.3333%; }
        [dir="rtl"] .offset-xs-10, [dir="rtl"]
        .push-xs-10 {
            left: auto;
            right: 83.3333%; }

        .pull-xs-10 {
            right: 83.3333%; }
        [dir="rtl"] .pull-xs-10 {
            right: auto;
            left: 83.3333%; }

        .col-xs-11 {
            width: 91.6667%; }

        .offset-xs-11,
        .push-xs-11 {
            left: 91.6667%; }
        [dir="rtl"] .offset-xs-11, [dir="rtl"]
        .push-xs-11 {
            left: auto;
            right: 91.6667%; }

        .pull-xs-11 {
            right: 91.6667%; }
        [dir="rtl"] .pull-xs-11 {
            right: auto;
            left: 91.6667%; }

        .col-xs-12 {
            width: 100%; }

        .offset-xs-12,
        .push-xs-12 {
            left: 100%; }
        [dir="rtl"] .offset-xs-12, [dir="rtl"]
        .push-xs-12 {
            left: auto;
            right: 100%; }

        .pull-xs-12 {
            right: 100%; }
        [dir="rtl"] .pull-xs-12 {
            right: auto;
            left: 100%; }

        .equal-height > [class*=col-xs] {
            display: table-cell;
            height: 100%; }

        .equal-height > .col-xs-13 {
            display: table-caption; }

        .block-row-xs-1 > * {
            width: 100%; }
        .block-row-xs-1 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-1 > :nth-of-type(1n+1) {
            clear: both; }

        .block-row-xs-2 > * {
            width: 50%; }
        .block-row-xs-2 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-2 > :nth-of-type(2n+1) {
            clear: both; }

        .block-row-xs-3 > * {
            width: 33.3333%; }
        .block-row-xs-3 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-3 > :nth-of-type(3n+1) {
            clear: both; }

        .block-row-xs-4 > * {
            width: 25%; }
        .block-row-xs-4 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-4 > :nth-of-type(4n+1) {
            clear: both; }

        .block-row-xs-5 > * {
            width: 20%; }
        .block-row-xs-5 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-5 > :nth-of-type(5n+1) {
            clear: both; }

        .block-row-xs-6 > * {
            width: 16.6667%; }
        .block-row-xs-6 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-6 > :nth-of-type(6n+1) {
            clear: both; }

        .block-row-xs-7 > * {
            width: 14.2857%; }
        .block-row-xs-7 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-7 > :nth-of-type(7n+1) {
            clear: both; }

        .block-row-xs-8 > * {
            width: 12.5%; }
        .block-row-xs-8 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-8 > :nth-of-type(8n+1) {
            clear: both; }

        .block-row-xs-9 > * {
            width: 11.1111%; }
        .block-row-xs-9 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-9 > :nth-of-type(9n+1) {
            clear: both; }

        .block-row-xs-10 > * {
            width: 10%; }
        .block-row-xs-10 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-10 > :nth-of-type(10n+1) {
            clear: both; }

        .block-row-xs-11 > * {
            width: 9.0909%; }
        .block-row-xs-11 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-11 > :nth-of-type(11n+1) {
            clear: both; }

        .block-row-xs-12 > * {
            width: 8.3333%; }
        .block-row-xs-12 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-xs-12 > :nth-of-type(12n+1) {
            clear: both; } }
    @media print and (min-width: 537px), screen and (min-width: 48em) {
        .col-s-1 {
            width: 8.3333%; }

        .offset-s-1,
        .push-s-1 {
            left: 8.3333%; }
        [dir="rtl"] .offset-s-1, [dir="rtl"]
        .push-s-1 {
            left: auto;
            right: 8.3333%; }

        .pull-s-1 {
            right: 8.3333%; }
        [dir="rtl"] .pull-s-1 {
            right: auto;
            left: 8.3333%; }

        .col-s-2 {
            width: 16.6667%; }

        .offset-s-2,
        .push-s-2 {
            left: 16.6667%; }
        [dir="rtl"] .offset-s-2, [dir="rtl"]
        .push-s-2 {
            left: auto;
            right: 16.6667%; }

        .pull-s-2 {
            right: 16.6667%; }
        [dir="rtl"] .pull-s-2 {
            right: auto;
            left: 16.6667%; }

        .col-s-3 {
            width: 25%; }

        .offset-s-3,
        .push-s-3 {
            left: 25%; }
        [dir="rtl"] .offset-s-3, [dir="rtl"]
        .push-s-3 {
            left: auto;
            right: 25%; }

        .pull-s-3 {
            right: 25%; }
        [dir="rtl"] .pull-s-3 {
            right: auto;
            left: 25%; }

        .col-s-4 {
            width: 33.3333%; }

        .offset-s-4,
        .push-s-4 {
            left: 33.3333%; }
        [dir="rtl"] .offset-s-4, [dir="rtl"]
        .push-s-4 {
            left: auto;
            right: 33.3333%; }

        .pull-s-4 {
            right: 33.3333%; }
        [dir="rtl"] .pull-s-4 {
            right: auto;
            left: 33.3333%; }

        .col-s-5 {
            width: 41.6667%; }

        .offset-s-5,
        .push-s-5 {
            left: 41.6667%; }
        [dir="rtl"] .offset-s-5, [dir="rtl"]
        .push-s-5 {
            left: auto;
            right: 41.6667%; }

        .pull-s-5 {
            right: 41.6667%; }
        [dir="rtl"] .pull-s-5 {
            right: auto;
            left: 41.6667%; }

        .col-s-6 {
            width: 50%; }

        .offset-s-6,
        .push-s-6 {
            left: 50%; }
        [dir="rtl"] .offset-s-6, [dir="rtl"]
        .push-s-6 {
            left: auto;
            right: 50%; }

        .pull-s-6 {
            right: 50%; }
        [dir="rtl"] .pull-s-6 {
            right: auto;
            left: 50%; }

        .col-s-7 {
            width: 58.3333%; }

        .offset-s-7,
        .push-s-7 {
            left: 58.3333%; }
        [dir="rtl"] .offset-s-7, [dir="rtl"]
        .push-s-7 {
            left: auto;
            right: 58.3333%; }

        .pull-s-7 {
            right: 58.3333%; }
        [dir="rtl"] .pull-s-7 {
            right: auto;
            left: 58.3333%; }

        .col-s-8 {
            width: 66.6667%; }

        .offset-s-8,
        .push-s-8 {
            left: 66.6667%; }
        [dir="rtl"] .offset-s-8, [dir="rtl"]
        .push-s-8 {
            left: auto;
            right: 66.6667%; }

        .pull-s-8 {
            right: 66.6667%; }
        [dir="rtl"] .pull-s-8 {
            right: auto;
            left: 66.6667%; }

        .col-s-9 {
            width: 75%; }

        .offset-s-9,
        .push-s-9 {
            left: 75%; }
        [dir="rtl"] .offset-s-9, [dir="rtl"]
        .push-s-9 {
            left: auto;
            right: 75%; }

        .pull-s-9 {
            right: 75%; }
        [dir="rtl"] .pull-s-9 {
            right: auto;
            left: 75%; }

        .col-s-10 {
            width: 83.3333%; }

        .offset-s-10,
        .push-s-10 {
            left: 83.3333%; }
        [dir="rtl"] .offset-s-10, [dir="rtl"]
        .push-s-10 {
            left: auto;
            right: 83.3333%; }

        .pull-s-10 {
            right: 83.3333%; }
        [dir="rtl"] .pull-s-10 {
            right: auto;
            left: 83.3333%; }

        .col-s-11 {
            width: 91.6667%; }

        .offset-s-11,
        .push-s-11 {
            left: 91.6667%; }
        [dir="rtl"] .offset-s-11, [dir="rtl"]
        .push-s-11 {
            left: auto;
            right: 91.6667%; }

        .pull-s-11 {
            right: 91.6667%; }
        [dir="rtl"] .pull-s-11 {
            right: auto;
            left: 91.6667%; }

        .col-s-12 {
            width: 100%; }

        .offset-s-12,
        .push-s-12 {
            left: 100%; }
        [dir="rtl"] .offset-s-12, [dir="rtl"]
        .push-s-12 {
            left: auto;
            right: 100%; }

        .pull-s-12 {
            right: 100%; }
        [dir="rtl"] .pull-s-12 {
            right: auto;
            left: 100%; }

        .equal-height > [class*=col-s] {
            display: table-cell;
            height: 100%; }

        .equal-height > .col-s-13 {
            display: table-caption; }

        .block-row-s-1 > * {
            width: 100%; }
        .block-row-s-1 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-1 > :nth-of-type(1n+1) {
            clear: both; }

        .block-row-s-2 > * {
            width: 50%; }
        .block-row-s-2 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-2 > :nth-of-type(2n+1) {
            clear: both; }

        .block-row-s-3 > * {
            width: 33.3333%; }
        .block-row-s-3 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-3 > :nth-of-type(3n+1) {
            clear: both; }

        .block-row-s-4 > * {
            width: 25%; }
        .block-row-s-4 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-4 > :nth-of-type(4n+1) {
            clear: both; }

        .block-row-s-5 > * {
            width: 20%; }
        .block-row-s-5 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-5 > :nth-of-type(5n+1) {
            clear: both; }

        .block-row-s-6 > * {
            width: 16.6667%; }
        .block-row-s-6 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-6 > :nth-of-type(6n+1) {
            clear: both; }

        .block-row-s-7 > * {
            width: 14.2857%; }
        .block-row-s-7 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-7 > :nth-of-type(7n+1) {
            clear: both; }

        .block-row-s-8 > * {
            width: 12.5%; }
        .block-row-s-8 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-8 > :nth-of-type(8n+1) {
            clear: both; }

        .block-row-s-9 > * {
            width: 11.1111%; }
        .block-row-s-9 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-9 > :nth-of-type(9n+1) {
            clear: both; }

        .block-row-s-10 > * {
            width: 10%; }
        .block-row-s-10 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-10 > :nth-of-type(10n+1) {
            clear: both; }

        .block-row-s-11 > * {
            width: 9.0909%; }
        .block-row-s-11 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-11 > :nth-of-type(11n+1) {
            clear: both; }

        .block-row-s-12 > * {
            width: 8.3333%; }
        .block-row-s-12 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-s-12 > :nth-of-type(12n+1) {
            clear: both; } }
    @media (min-width: 62em) {
        .col-m-1 {
            width: 8.3333%; }

        .offset-m-1,
        .push-m-1 {
            left: 8.3333%; }
        [dir="rtl"] .offset-m-1, [dir="rtl"]
        .push-m-1 {
            left: auto;
            right: 8.3333%; }

        .pull-m-1 {
            right: 8.3333%; }
        [dir="rtl"] .pull-m-1 {
            right: auto;
            left: 8.3333%; }

        .col-m-2 {
            width: 16.6667%; }

        .offset-m-2,
        .push-m-2 {
            left: 16.6667%; }
        [dir="rtl"] .offset-m-2, [dir="rtl"]
        .push-m-2 {
            left: auto;
            right: 16.6667%; }

        .pull-m-2 {
            right: 16.6667%; }
        [dir="rtl"] .pull-m-2 {
            right: auto;
            left: 16.6667%; }

        .col-m-3 {
            width: 25%; }

        .offset-m-3,
        .push-m-3 {
            left: 25%; }
        [dir="rtl"] .offset-m-3, [dir="rtl"]
        .push-m-3 {
            left: auto;
            right: 25%; }

        .pull-m-3 {
            right: 25%; }
        [dir="rtl"] .pull-m-3 {
            right: auto;
            left: 25%; }

        .col-m-4 {
            width: 33.3333%; }

        .offset-m-4,
        .push-m-4 {
            left: 33.3333%; }
        [dir="rtl"] .offset-m-4, [dir="rtl"]
        .push-m-4 {
            left: auto;
            right: 33.3333%; }

        .pull-m-4 {
            right: 33.3333%; }
        [dir="rtl"] .pull-m-4 {
            right: auto;
            left: 33.3333%; }

        .col-m-5 {
            width: 41.6667%; }

        .offset-m-5,
        .push-m-5 {
            left: 41.6667%; }
        [dir="rtl"] .offset-m-5, [dir="rtl"]
        .push-m-5 {
            left: auto;
            right: 41.6667%; }

        .pull-m-5 {
            right: 41.6667%; }
        [dir="rtl"] .pull-m-5 {
            right: auto;
            left: 41.6667%; }

        .col-m-6 {
            width: 50%; }

        .offset-m-6,
        .push-m-6 {
            left: 50%; }
        [dir="rtl"] .offset-m-6, [dir="rtl"]
        .push-m-6 {
            left: auto;
            right: 50%; }

        .pull-m-6 {
            right: 50%; }
        [dir="rtl"] .pull-m-6 {
            right: auto;
            left: 50%; }

        .col-m-7 {
            width: 58.3333%; }

        .offset-m-7,
        .push-m-7 {
            left: 58.3333%; }
        [dir="rtl"] .offset-m-7, [dir="rtl"]
        .push-m-7 {
            left: auto;
            right: 58.3333%; }

        .pull-m-7 {
            right: 58.3333%; }
        [dir="rtl"] .pull-m-7 {
            right: auto;
            left: 58.3333%; }

        .col-m-8 {
            width: 66.6667%; }

        .offset-m-8,
        .push-m-8 {
            left: 66.6667%; }
        [dir="rtl"] .offset-m-8, [dir="rtl"]
        .push-m-8 {
            left: auto;
            right: 66.6667%; }

        .pull-m-8 {
            right: 66.6667%; }
        [dir="rtl"] .pull-m-8 {
            right: auto;
            left: 66.6667%; }

        .col-m-9 {
            width: 75%; }

        .offset-m-9,
        .push-m-9 {
            left: 75%; }
        [dir="rtl"] .offset-m-9, [dir="rtl"]
        .push-m-9 {
            left: auto;
            right: 75%; }

        .pull-m-9 {
            right: 75%; }
        [dir="rtl"] .pull-m-9 {
            right: auto;
            left: 75%; }

        .col-m-10 {
            width: 83.3333%; }

        .offset-m-10,
        .push-m-10 {
            left: 83.3333%; }
        [dir="rtl"] .offset-m-10, [dir="rtl"]
        .push-m-10 {
            left: auto;
            right: 83.3333%; }

        .pull-m-10 {
            right: 83.3333%; }
        [dir="rtl"] .pull-m-10 {
            right: auto;
            left: 83.3333%; }

        .col-m-11 {
            width: 91.6667%; }

        .offset-m-11,
        .push-m-11 {
            left: 91.6667%; }
        [dir="rtl"] .offset-m-11, [dir="rtl"]
        .push-m-11 {
            left: auto;
            right: 91.6667%; }

        .pull-m-11 {
            right: 91.6667%; }
        [dir="rtl"] .pull-m-11 {
            right: auto;
            left: 91.6667%; }

        .col-m-12 {
            width: 100%; }

        .offset-m-12,
        .push-m-12 {
            left: 100%; }
        [dir="rtl"] .offset-m-12, [dir="rtl"]
        .push-m-12 {
            left: auto;
            right: 100%; }

        .pull-m-12 {
            right: 100%; }
        [dir="rtl"] .pull-m-12 {
            right: auto;
            left: 100%; }

        .equal-height > [class*=col-m] {
            display: table-cell;
            height: 100%; }

        .equal-height > .col-m-13 {
            display: table-caption; }

        .block-row-m-1 > * {
            width: 100%; }
        .block-row-m-1 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-1 > :nth-of-type(1n+1) {
            clear: both; }

        .block-row-m-2 > * {
            width: 50%; }
        .block-row-m-2 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-2 > :nth-of-type(2n+1) {
            clear: both; }

        .block-row-m-3 > * {
            width: 33.3333%; }
        .block-row-m-3 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-3 > :nth-of-type(3n+1) {
            clear: both; }

        .block-row-m-4 > * {
            width: 25%; }
        .block-row-m-4 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-4 > :nth-of-type(4n+1) {
            clear: both; }

        .block-row-m-5 > * {
            width: 20%; }
        .block-row-m-5 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-5 > :nth-of-type(5n+1) {
            clear: both; }

        .block-row-m-6 > * {
            width: 16.6667%; }
        .block-row-m-6 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-6 > :nth-of-type(6n+1) {
            clear: both; }

        .block-row-m-7 > * {
            width: 14.2857%; }
        .block-row-m-7 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-7 > :nth-of-type(7n+1) {
            clear: both; }

        .block-row-m-8 > * {
            width: 12.5%; }
        .block-row-m-8 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-8 > :nth-of-type(8n+1) {
            clear: both; }

        .block-row-m-9 > * {
            width: 11.1111%; }
        .block-row-m-9 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-9 > :nth-of-type(9n+1) {
            clear: both; }

        .block-row-m-10 > * {
            width: 10%; }
        .block-row-m-10 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-10 > :nth-of-type(10n+1) {
            clear: both; }

        .block-row-m-11 > * {
            width: 9.0909%; }
        .block-row-m-11 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-11 > :nth-of-type(11n+1) {
            clear: both; }

        .block-row-m-12 > * {
            width: 8.3333%; }
        .block-row-m-12 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-m-12 > :nth-of-type(12n+1) {
            clear: both; } }
    @media (min-width: 75em) {
        .col-l-1 {
            width: 8.3333%; }

        .offset-l-1,
        .push-l-1 {
            left: 8.3333%; }
        [dir="rtl"] .offset-l-1, [dir="rtl"]
        .push-l-1 {
            left: auto;
            right: 8.3333%; }

        .pull-l-1 {
            right: 8.3333%; }
        [dir="rtl"] .pull-l-1 {
            right: auto;
            left: 8.3333%; }

        .col-l-2 {
            width: 16.6667%; }

        .offset-l-2,
        .push-l-2 {
            left: 16.6667%; }
        [dir="rtl"] .offset-l-2, [dir="rtl"]
        .push-l-2 {
            left: auto;
            right: 16.6667%; }

        .pull-l-2 {
            right: 16.6667%; }
        [dir="rtl"] .pull-l-2 {
            right: auto;
            left: 16.6667%; }

        .col-l-3 {
            width: 25%; }

        .offset-l-3,
        .push-l-3 {
            left: 25%; }
        [dir="rtl"] .offset-l-3, [dir="rtl"]
        .push-l-3 {
            left: auto;
            right: 25%; }

        .pull-l-3 {
            right: 25%; }
        [dir="rtl"] .pull-l-3 {
            right: auto;
            left: 25%; }

        .col-l-4 {
            width: 33.3333%; }

        .offset-l-4,
        .push-l-4 {
            left: 33.3333%; }
        [dir="rtl"] .offset-l-4, [dir="rtl"]
        .push-l-4 {
            left: auto;
            right: 33.3333%; }

        .pull-l-4 {
            right: 33.3333%; }
        [dir="rtl"] .pull-l-4 {
            right: auto;
            left: 33.3333%; }

        .col-l-5 {
            width: 41.6667%; }

        .offset-l-5,
        .push-l-5 {
            left: 41.6667%; }
        [dir="rtl"] .offset-l-5, [dir="rtl"]
        .push-l-5 {
            left: auto;
            right: 41.6667%; }

        .pull-l-5 {
            right: 41.6667%; }
        [dir="rtl"] .pull-l-5 {
            right: auto;
            left: 41.6667%; }

        .col-l-6 {
            width: 50%; }

        .offset-l-6,
        .push-l-6 {
            left: 50%; }
        [dir="rtl"] .offset-l-6, [dir="rtl"]
        .push-l-6 {
            left: auto;
            right: 50%; }

        .pull-l-6 {
            right: 50%; }
        [dir="rtl"] .pull-l-6 {
            right: auto;
            left: 50%; }

        .col-l-7 {
            width: 58.3333%; }

        .offset-l-7,
        .push-l-7 {
            left: 58.3333%; }
        [dir="rtl"] .offset-l-7, [dir="rtl"]
        .push-l-7 {
            left: auto;
            right: 58.3333%; }

        .pull-l-7 {
            right: 58.3333%; }
        [dir="rtl"] .pull-l-7 {
            right: auto;
            left: 58.3333%; }

        .col-l-8 {
            width: 66.6667%; }

        .offset-l-8,
        .push-l-8 {
            left: 66.6667%; }
        [dir="rtl"] .offset-l-8, [dir="rtl"]
        .push-l-8 {
            left: auto;
            right: 66.6667%; }

        .pull-l-8 {
            right: 66.6667%; }
        [dir="rtl"] .pull-l-8 {
            right: auto;
            left: 66.6667%; }

        .col-l-9 {
            width: 75%; }

        .offset-l-9,
        .push-l-9 {
            left: 75%; }
        [dir="rtl"] .offset-l-9, [dir="rtl"]
        .push-l-9 {
            left: auto;
            right: 75%; }

        .pull-l-9 {
            right: 75%; }
        [dir="rtl"] .pull-l-9 {
            right: auto;
            left: 75%; }

        .col-l-10 {
            width: 83.3333%; }

        .offset-l-10,
        .push-l-10 {
            left: 83.3333%; }
        [dir="rtl"] .offset-l-10, [dir="rtl"]
        .push-l-10 {
            left: auto;
            right: 83.3333%; }

        .pull-l-10 {
            right: 83.3333%; }
        [dir="rtl"] .pull-l-10 {
            right: auto;
            left: 83.3333%; }

        .col-l-11 {
            width: 91.6667%; }

        .offset-l-11,
        .push-l-11 {
            left: 91.6667%; }
        [dir="rtl"] .offset-l-11, [dir="rtl"]
        .push-l-11 {
            left: auto;
            right: 91.6667%; }

        .pull-l-11 {
            right: 91.6667%; }
        [dir="rtl"] .pull-l-11 {
            right: auto;
            left: 91.6667%; }

        .col-l-12 {
            width: 100%; }

        .offset-l-12,
        .push-l-12 {
            left: 100%; }
        [dir="rtl"] .offset-l-12, [dir="rtl"]
        .push-l-12 {
            left: auto;
            right: 100%; }

        .pull-l-12 {
            right: 100%; }
        [dir="rtl"] .pull-l-12 {
            right: auto;
            left: 100%; }

        .equal-height > [class*=col-l] {
            display: table-cell;
            height: 100%; }

        .equal-height > .col-l-13 {
            display: table-caption; }

        .block-row-l-1 > * {
            width: 100%; }
        .block-row-l-1 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-1 > :nth-of-type(1n+1) {
            clear: both; }

        .block-row-l-2 > * {
            width: 50%; }
        .block-row-l-2 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-2 > :nth-of-type(2n+1) {
            clear: both; }

        .block-row-l-3 > * {
            width: 33.3333%; }
        .block-row-l-3 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-3 > :nth-of-type(3n+1) {
            clear: both; }

        .block-row-l-4 > * {
            width: 25%; }
        .block-row-l-4 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-4 > :nth-of-type(4n+1) {
            clear: both; }

        .block-row-l-5 > * {
            width: 20%; }
        .block-row-l-5 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-5 > :nth-of-type(5n+1) {
            clear: both; }

        .block-row-l-6 > * {
            width: 16.6667%; }
        .block-row-l-6 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-6 > :nth-of-type(6n+1) {
            clear: both; }

        .block-row-l-7 > * {
            width: 14.2857%; }
        .block-row-l-7 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-7 > :nth-of-type(7n+1) {
            clear: both; }

        .block-row-l-8 > * {
            width: 12.5%; }
        .block-row-l-8 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-8 > :nth-of-type(8n+1) {
            clear: both; }

        .block-row-l-9 > * {
            width: 11.1111%; }
        .block-row-l-9 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-9 > :nth-of-type(9n+1) {
            clear: both; }

        .block-row-l-10 > * {
            width: 10%; }
        .block-row-l-10 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-10 > :nth-of-type(10n+1) {
            clear: both; }

        .block-row-l-11 > * {
            width: 9.0909%; }
        .block-row-l-11 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-11 > :nth-of-type(11n+1) {
            clear: both; }

        .block-row-l-12 > * {
            width: 8.3333%; }
        .block-row-l-12 > :nth-of-type(n+1) {
            clear: none; }
        .block-row-l-12 > :nth-of-type(12n+1) {
            clear: both; } }




    button,
    input[type="submit"],
    input[type="button"],
    input[type="reset"] {
        -webkit-appearance: none;
        border-radius: 0;
        color: inherit;
        cursor: pointer;
        display: inline-block;
        min-height: 2rem;
        padding: 0 1rem;
        margin-bottom: 0;
        background: #dadada;
        border: solid 1px silver;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        text-decoration: none; }
    button:hover,
    input[type="submit"]:hover,
    input[type="button"]:hover,
    input[type="reset"]:hover {
        background-color: #cdcdcd; }
    button:active,
    input[type="submit"]:active,
    input[type="button"]:active,
    input[type="reset"]:active {
        background-color: #e7e7e7;
        outline: none; }
    button[disabled],
    input[type="submit"][disabled],
    input[type="button"][disabled],
    input[type="reset"][disabled] {
        background-color: #e7e7e7;
        color: #5d5d5d;
        cursor: not-allowed;
        opacity: 1; }
    .input-group button, .input-group
    input[type="submit"], .input-group
    input[type="button"], .input-group
    input[type="reset"] {
        min-width: 100%; }

    input[type="submit"], input[type="reset"], input[type="button"] {
        max-width: none;
        width: auto; }

    .btn-group > * {
        float: left; }
    [dir="rtl"] .btn-group > * {
        float: right; }

    pre,
    code,
    samp,
    kbd {
        padding: .5rem;
        font-size: 1rem;
        background-color: #f7f7f9;
        border: 1px solid silver;
        font-family: monospace, monospace;
        color: #950b2f; }

    code > kbd {
        background-color: #e8e8ee; }

    code,
    samp,
    kbd {
        padding: .0667rem .25rem; }

    kbd {
        white-space: nowrap; }

    pre {
        overflow-x: auto; }
    pre code,
    pre samp {
        padding: 0;
        border: none; }
    pre code {
        word-wrap: normal;
        white-space: pre; }

    .pre-scrollable {
        max-height: 20rem;
        overflow-y: scroll; }

    fieldset {
        border: 0;
        margin: 0;
        padding: 0; }

    legend {
        display: block;
        width: 100%;
        margin-bottom: 1rem; }

    label {
        display: block;
        margin-bottom: 1rem; }
    label[for] {
        cursor: pointer; }
    label > input,
    label > input[type='checkbox'],
    label > input[type='radio'],
    label > select {
        display: inline-block;
        margin: 0 1rem 0 0;
        vertical-align: text-top; }
    [dir=rtl] label > input, [dir=rtl]
    label > input[type='checkbox'], [dir=rtl]
    label > input[type='radio'], [dir=rtl]
    label > select {
        margin: 0 0 0 1rem; }

    select,
    textarea,
    input,
    .readonly {
        display: block;
        height: 2rem;
        padding: 0.25rem;
        width: 100%;
        margin-bottom: 1rem;
        background: white;
        border: 1px solid silver;
        border-radius: 0;
        color: #222222;
        font-family: inherit; }
    fieldset[disabled] select, select[disabled], fieldset[disabled]
    textarea,
    textarea[disabled], fieldset[disabled]
    input,
    input[disabled], fieldset[disabled]
    .readonly,
    .readonly[disabled] {
        background: #ebebeb;
        border-color: silver;
        color: silver;
        cursor: not-allowed;
        opacity: 1; }

    input[type='file']::-ms-value {
        background: white;
        border: none; }

    input[type='file']::-ms-browse {
        -webkit-appearance: none;
        background: #dadada;
        border: solid 1px silver;
        color: #222222; }
    input[type='file']::-ms-browse:active {
        background-color: #e7e7e7; }

    input[type='file']::-webkit-file-upload-button {
        -webkit-appearance: none;
        border-radius: 0;
        background: #dadada;
        border: solid 1px silver;
        color: #222222; }
    input[type='file']::-webkit-file-upload-button:active {
        background-color: #e7e7e7; }

    input[type='color'] {
        max-width: 6.563rem; }

    input[type='radio'],
    input[type='checkbox'] {
        height: 1.334rem;
        min-width: 1.334rem;
        margin-bottom: 1.1rem;
        padding: 0;
        width: auto; }

    input[type='radio'] {
        border-radius: 100%;
        border: none \9; }

    input[type='range'] {
        border: 1px solid transparent;
        border: 1px solid silver \9;
        background-color: transparent;
        background-color: white \9;
        padding: 0.25rem 0;
        padding: 0.25rem \9; }

    _::-ms-reveal,
    input[type='range'] {
        border: 1px solid transparent; }

    select,
    textarea,
    input[type='text'],
    input[type='search'],
    input[type='datetime'],
    input[type='datetime-local'],
    input[type='date'],
    input[type='week'],
    input[type='month'],
    input[type='time'],
    input[type='number'],
    input[type='password'],
    input[type='tel'],
    input[type='email'],
    input[type='url'],
    input[type='color'] {
        -webkit-appearance: none; }

    select option {
        height: 100%; }

    [multiple] {
        height: auto; }

    [multiple] option {
        height: auto; }

    textarea {
        height: auto;
        min-height: 5.25rem;
        resize: both; }

    textarea.vertical {
        resize: vertical; }
    textarea.no-resize {
        resize: none; }

    .readonly,
    [readonly] {
        border-color: #ebebeb;
        cursor: not-allowed; }

    ::-webkit-input-placeholder {
        color: #767676;
        opacity: 1; }

    ::-moz-placeholder {
        color: #767676;
        opacity: 1; }

    :-ms-input-placeholder {
        color: #767676;
        opacity: 1; }

    ::placeholder {
        color: #767676;
        opacity: 1; }

    @-moz-document url-prefix() {
        input[type='color'] {
            padding: 0; }

        input[type='file'] {
            height: auto;
            min-height: 2rem; } }

    @media (-webkit-min-device-pixel-ratio: 0) {
        input[type='color'] {
            padding: 0; }
        input[type='color']::-webkit-color-swatch-wrapper {
            padding: 0; }
        input[type='color']::-webkit-color-swatch {
            border: none; }

        select {
            background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMSIgaGVpZ2h0PSIxMC41Ij48cG9seWdvbiBmaWxsPSIjMjIyIiBwb2ludHM9IjExLDAgNS41LDkgMCwwIi8+PC9zdmc+");
            background-repeat: no-repeat;
            background-position: right .6rem center;
            padding-right: 1.67rem; }
        [dir=rtl] select {
            background-position: .6rem center;
            padding-right: 0;
            padding-left: 1.67rem; }
        select[multiple] {
            background-image: none;
            padding-left: 0;
            padding-right: 0; } }
    input.inline-block,
    select.inline-block {
        width: auto; }

    .form-actions {
        margin: 1rem 0;
        padding: 1rem 0; }

    .input-group,
    .btn-group {
        position: relative;
        display: table;
        border-collapse: separate;
        width: 100%;
        margin-bottom: 1rem; }

    .btn-group {
        width: auto; }

    .input-group > *,
    .btn-group > * {
        display: table-cell;
        margin-bottom: 0; }

    .input-group-addon {
        width: 1%;
        white-space: nowrap;
        vertical-align: middle; }
    .input-group-addon > * {
        margin-bottom: 0 !important; }

    .supplement {
        padding: 0 1rem;
        line-height: 1.4;
        background: #dadada;
        border: solid 1px silver; }
    html:not([dir=rtl]) .supplement:first-child {
        border-right: none; }
    html:not([dir=rtl]) .supplement:last-child {
        border-left: none; }
    [dir=rtl] .supplement:first-child {
        border-left: none; }
    [dir=rtl] .supplement:last-child {
        border-right: none; }

    ul,
    ol {
        margin: 1rem 0;
        padding-left: 2.5rem; }
    [dir="rtl"] ul, [dir="rtl"]
    ol {
        padding-left: 0;
        padding-right: 2.5rem; }

    ul ul,
    ol ol {
        margin: 0; }

    ul.no-bullets,
    ol.no-bullets {
        padding-left: 0; }
    [dir="rtl"] ul.no-bullets, [dir="rtl"]
    ol.no-bullets {
        padding-right: 0; }
    ul.no-bullets > li,
    ol.no-bullets > li {
        list-style: none; }

    ul.colored,
    ol.colored {
        padding-left: 2.5rem; }
    ul.colored > li,
    ol.colored > li {
        list-style-type: none;
        position: relative; }
    ul.colored > li:before,
    ol.colored > li:before {
        position: absolute;
        top: .1rem;
        left: -1rem;
        -webkit-margin-start: -.25rem;
        content: "\25cf";
        color: #00a9ec;
        font-size: .8rem;
        text-align: right;
        text-decoration: none; }
    [dir="rtl"] ul.colored > li:before, [dir="rtl"]
    ol.colored > li:before {
        left: auto;
        right: -1rem;
        text-align: left; }

    ol.colored {
        counter-reset: foo; }
    ol.colored > li {
        counter-increment: foo; }
    ol.colored > li:before {
        content: counter(foo) ".";
        top: 0;
        left: -3.125rem;
        width: 2.5rem;
        -webkit-margin-start: 0;
        font-size: 1rem; }
    [dir="rtl"] ol.colored > li:before {
        right: -3.125rem; }

    dt, dd {
        min-height: 1.4rem; }




    .trans,
    .collapse {
        -webkit-transition: height .5s ease, width .5s ease;
        transition: height .5s ease, width .5s ease; }

    .expand,
    .collapse {
        display: block;
        height: auto;
        margin-top: 0;
        overflow: hidden;
        position: relative;
        width: auto; }

    .collapse {
        height: 0; }
    .collapse.width {
        height: auto;
        width: 0; }



    @media print and (max-width: 536px), screen and (max-width: 47.99em) {
        /*
             * Force the columns to display as rows on small viewports.
         * Headers are applied with data attributes.
             */
        [data-table-list] {
            opacity: 0; }



        .clearfix:before, .container:before, .modal-ajax.container:before,
        .modal-iframe:before,
        .container-full:before, .row:before,
        [class*="block-row-"]:before, .alert:before, .tabs > ul:before, .clearfix:after, .container:after, .modal-ajax.container:after,
        .modal-iframe:after,
        .container-full:after, .row:after,
        [class*="block-row-"]:after, .alert:after, .tabs > ul:after {
            content: "";
            display: table; }
        .clearfix:after, .container:after, .modal-ajax.container:after,
        .modal-iframe:after,
        .container-full:after, .row:after,
        [class*="block-row-"]:after, .alert:after, .tabs > ul:after {
            clear: both; }

        .push {
            float: right; }
        [dir="rtl"] .push {
            float: left; }

        .pull {
            float: left; }
        [dir="rtl"] .pull {
            float: right; }

        .push-xxs {
            float: right; }
        [dir="rtl"] .push-xxs {
            float: left; }

        .pull-xxs {
            float: left; }
        [dir="rtl"] .pull-xxs {
            float: right; }

        @media (max-width: 37.49em) {
            .push-xxs-only {
                float: right; }
            [dir="rtl"] .push-xxs-only {
                float: left; }

            .pull-xxs-only {
                float: left; }
            [dir="rtl"] .pull-xxs-only {
                float: right; } }
        @media print and (min-width: 536px), screen and (min-width: 37.5em) {
            .push-xs {
                float: right; }
            [dir="rtl"] .push-xs {
                float: left; }

            .pull-xs {
                float: left; }
            [dir="rtl"] .pull-xs {
                float: right; } }
        @media print and (min-width: 536px) and (max-width: 536px), screen and (min-width: 37.5em) and (max-width: 47.99em) {
            .push-xs-only {
                float: right; }
            [dir="rtl"] .push-xs-only {
                float: left; }

            .pull-xs-only {
                float: left; }
            [dir="rtl"] .pull-xs-only {
                float: right; } }
        @media print and (min-width: 537px), screen and (min-width: 48em) {
            .push-s {
                float: right; }
            [dir="rtl"] .push-s {
                float: left; }

            .pull-s {
                float: left; }
            [dir="rtl"] .pull-s {
                float: right; } }
        @media print and (min-width: 537px) and (max-width: 61.99em), screen and (min-width: 48em) and (max-width: 61.99em) {
            .push-s-only {
                float: right; }
            [dir="rtl"] .push-s-only {
                float: left; }

            .pull-s-only {
                float: left; }
            [dir="rtl"] .pull-s-only {
                float: right; } }
        @media (min-width: 62em) {
            .push-m {
                float: right; }
            [dir="rtl"] .push-m {
                float: left; }

            .pull-m {
                float: left; }
            [dir="rtl"] .pull-m {
                float: right; } }
        @media (min-width: 62em) and (max-width: 74.99em) {
            .push-m-only {
                float: right; }
            [dir="rtl"] .push-m-only {
                float: left; }

            .pull-m-only {
                float: left; }
            [dir="rtl"] .pull-m-only {
                float: right; } }
        @media (min-width: 75em) {
            .push-l {
                float: right; }
            [dir="rtl"] .push-l {
                float: left; }

            .pull-l {
                float: left; }
            [dir="rtl"] .pull-l {
                float: right; } }
        .block {
            display: block; }

        .inline-block {
            display: inline-block; }

        .inline {
            display: inline; }

        .block-xxs {
            display: block; }

        .inline-block-xxs {
            display: inline-block; }

        .inline-xxs {
            display: inline; }

        @media (max-width: 37.49em) {
            .block-xxs-only {
                display: block; }

            .inline-block-xxs-only {
                display: inline-block; }

            .inline-xxs-only {
                display: inline; } }
        @media print and (min-width: 536px), screen and (min-width: 37.5em) {
            .block-xs {
                display: block; }

            .inline-block-xs {
                display: inline-block; }

            .inline-xs {
                display: inline; } }
        @media print and (min-width: 536px) and (max-width: 536px), screen and (min-width: 37.5em) and (max-width: 47.99em) {
            .block-xs-only {
                display: block; }

            .inline-block-xs-only {
                display: inline-block; }

            .inline-xs-only {
                display: inline; } }
        @media print and (min-width: 537px), screen and (min-width: 48em) {
            .block-s {
                display: block; }

            .inline-block-s {
                display: inline-block; }

            .inline-s {
                display: inline; } }
        @media print and (min-width: 537px) and (max-width: 61.99em), screen and (min-width: 48em) and (max-width: 61.99em) {
            .block-s-only {
                display: block; }

            .inline-block-s-only {
                display: inline-block; }

            .inline-s-only {
                display: inline; } }
        @media (min-width: 62em) {
            .block-m {
                display: block; }

            .inline-block-m {
                display: inline-block; }

            .inline-m {
                display: inline; } }
        @media (min-width: 62em) and (max-width: 74.99em) {
            .block-m-only {
                display: block; }

            .inline-block-m-only {
                display: inline-block; }

            .inline-m-only {
                display: inline; } }
        @media (min-width: 75em) {
            .block-l {
                display: block; }

            .inline-block-l {
                display: inline-block; }

            .inline-l {
                display: inline; } }
        .text-pull {
            text-align: left; }
        [dir="rtl"] .text-pull {
            text-align: right; }

        .text-push {
            text-align: right; }
        [dir="rtl"] .text-push {
            text-align: left; }

        .text-center {
            text-align: center; }

        .text-xxs-pull {
            text-align: left; }
        [dir="rtl"] .text-xxs-pull {
            text-align: right; }

        .text-xxs-push {
            text-align: right; }
        [dir="rtl"] .text-xxs-push {
            text-align: left; }

        .text-xxs-center {
            text-align: center; }

        @media (max-width: 37.49em) {
            .text-xxs-pull-only {
                text-align: left; }
            [dir="rtl"] .text-xxs-pull-only {
                text-align: right; }

            .text-xxs-push-only {
                text-align: right; }
            [dir="rtl"] .text-xxs-push-only {
                text-align: left; }

            .text-xxs-center-only {
                text-align: center; } }
        @media print and (min-width: 536px), screen and (min-width: 37.5em) {
            .text-xs-pull {
                text-align: left; }
            [dir="rtl"] .text-xs-pull {
                text-align: right; }

            .text-xs-push {
                text-align: right; }
            [dir="rtl"] .text-xs-push {
                text-align: left; }

            .text-xs-center {
                text-align: center; } }
        @media print and (min-width: 536px) and (max-width: 536px), screen and (min-width: 37.5em) and (max-width: 47.99em) {
            .text-xs-pull {
                text-align: left; }
            [dir="rtl"] .text-xs-pull {
                text-align: right; }

            .text-xs-push {
                text-align: right; }
            [dir="rtl"] .text-xs-push {
                text-align: left; }

            .text-xs-center {
                text-align: center; } }
        @media print and (min-width: 537px), screen and (min-width: 48em) {
            .text-s-pull {
                text-align: left; }
            [dir="rtl"] .text-s-pull {
                text-align: right; }

            .text-s-push {
                text-align: right; }
            [dir="rtl"] .text-s-push {
                text-align: left; }

            .text-s-center {
                text-align: center; } }
        @media print and (min-width: 537px) and (max-width: 61.99em), screen and (min-width: 48em) and (max-width: 61.99em) {
            .text-s-pull {
                text-align: left; }
            [dir="rtl"] .text-s-pull {
                text-align: right; }

            .text-s-push {
                text-align: right; }
            [dir="rtl"] .text-s-push {
                text-align: left; }

            .text-s-center {
                text-align: center; } }
        @media (min-width: 62em) {
            .text-m-pull {
                text-align: left; }
            [dir="rtl"] .text-m-pull {
                text-align: right; }

            .text-m-push {
                text-align: right; }
            [dir="rtl"] .text-m-push {
                text-align: left; }

            .text-m-center {
                text-align: center; } }
        @media (min-width: 62em) and (max-width: 74.99em) {
            .text-m-pull {
                text-align: left; }
            [dir="rtl"] .text-m-pull {
                text-align: right; }

            .text-m-push {
                text-align: right; }
            [dir="rtl"] .text-m-push {
                text-align: left; }

            .text-m-center {
                text-align: center; } }
        @media (min-width: 75em) {
            .text-l-pull {
                text-align: left; }
            [dir="rtl"] .text-l-pull {
                text-align: right; }

            .text-l-push {
                text-align: right; }
            [dir="rtl"] .text-l-push {
                text-align: left; }

            .text-l-center {
                text-align: center; } }
        .grid-state-indicator {
            position: absolute;
            top: -9999px;
            height: 1px;
            width: 0; }




    </style>