<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <link rel="shortcut icon" href="<?php echo STATIC_URL ?>favicon.ico" />
        <!-- css -->
        <link href="<?php echo STATIC_URL ?>preview/css/general.css" rel="stylesheet" />
        <link href="<?php echo STATIC_URL ?>preview/css/servicios.css" rel="stylesheet" />
    </head>
    <body>
        <div class="page">
            <?= $this->layout()->content ?>
        </div>
    </body>
</html>
