<div class="head">
    <img class="img-head"
         src="<?= STATIC_URL ?>preview/img/basico240/title.jpg">
</div>


<!--/////////////////REGISTRO ///////////////////////////////7-->
<div class="banner-second-section">
    <div  class="item-banner">
        <a href="/preview/servicios/registrate">
            <img class="img-banner" src="<?= DINAMIC_URL ?>/movistar-mas_240x48.gif" alt="movistarMas" />
        </a>
    </div>
</div>
<div id="section">
    <div class="spance-line-item"></div>
</div>


<!--/////////////////REGISTRO ///////////////////////////////7-->



<div class="spance-line"></div>


<div class="banner">
    <?php foreach (array(1, 2, 3) as $i) : ?>
        <div  class="item-banner">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['url'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banner/basico240/<?= $item['ImgBasico240'] ?>" alt="<?= $item['titulo'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<!--/////////////////TOP LINK ///////////////////////////////7-->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Top Link</div>
    </div>
    <div class="spance-line-item"></div>
    <?php foreach ($this->SoapLink as $item): ?>
        <div class="list">    
            <a class="list-link" href="<?= $item['url'] ?>">
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<!--/////////////////TOP LINK ///////////////////////////////7-->
<div id="section">   
    <div class="spance-line-item"></div>
    <div class="banner">
        <div  class="item-banner">
            <a href="<?= $this->SoapMovistarBanner['url'] ?>">
                <img class="img-banner" src="<?= DINAMIC_URL ?>banner/basico240/<?= $this->SoapMovistarBanner['ImgBasico240'] ?>" alt="<?= $this->SoapMovistarBanner['titulo'] ?>" />
            </a>

        </div>
    </div>
</div>

<div id="section">   
    <div class="title-list">
        <div class="title-item">Servicios</div>
    </div>
    <div class="spance-line-item"></div>
    <?php foreach ($this->SoapServicio as $item): ?>
        <div class="list">
            <a class="list-link" href="<?= $item['url'] ?>"> 
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>


</div>

<!-- música -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Musica</div>
    </div>
    <div class="title-clic">(Dando clic en la canción ya estás comprando! Costo S/. 4.75 )</div>
    <div class="spance-line-item"></div>



    <?php foreach ($this->SoapMusica as $item): ?>
        <div class="list">
            <a class="list-link"
               href="<?= $item["url"] ?>"><?= $item["titulo"] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<!-- secction -->
<div id="section">   
    <div class="title-list">
        <div class="title-item">Juegos</div>
    </div>
    <div class="title-clic">(Dando clic al juego ya estás comprando! Costo S/. 5.00)</div>
    <div class="spance-line-item"></div>


    <?php foreach ($this->SoapJuego as $item): ?>
        <div class="list">
            <a class="text-link"
               href="<?= $item["url"] ?>"><?= $item["nombre"] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>

<div class="banner">
    <?php foreach (array(4) as $i) : ?>
        <div  class="item-banner">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['url'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banner/basico240/<?= $item['ImgBasico240'] ?>" alt="<?= $item['titulo'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<!-- otros -->
<div id="section-other">
    <div class="spance-line-item"></div>
    <?php foreach ($this->SoapText as $item): ?>
        <div class="list">
            <a class="list-link" href="<?= $item['url'] ?>">
                <?= $item['descripcion'] ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>
<div class="banner">
    <?php foreach (array(5) as $i) : ?>
        <div  class="item-banner">
            <div class="flex-container">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($this->SoapBanners[$i] as $item): ?>
                            <li>
                                <a href="<?= $item['url'] ?>"><img class="img-banner" src="<?= DINAMIC_URL ?>banner/basico240/<?= $item['ImgBasico240'] ?>" alt="<?= $item['titulo'] ?>" /></a>
                            </li>
                        <?php endforeach; ?>       
                    </ul>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

