
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo STATIC_URL?>/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
        <title>Error de acceso</title>
        <style>
            body {background: #f9fee8;margin: 0; padding: 20px; text-align:center; font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#666666;}
            .error_page {width: 600px; padding: 50px; margin: auto;}
            .error_page h1 {margin: 20px 0 0;}
            .error_page p {margin: 10px 0; padding: 0;}		
            a {color: #9caa6d; text-decoration:none;}
            a:hover {color: #9caa6d; text-decoration:underline;}
        </style>

    </head>
    <body class="login">
        <div class="error_page">
            <img alt="Kidmondo_face_sad" src="http://kidmondo.com/wp-content/themes/kidmondo2/images/kidmondo_face_sad.gif" />
            <?php echo $this->layout()->content; ?>
            
        </div>
    </body>
</html>