<h3 class="admin-title">Listado de Text Link</h3>
<?php $this->getMesseger(); ?>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Text Link</h2>
        <a class="btn-admin" title="Nuevo Juego" href="/admin/text/new">Nuevo Text Link</a>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Descripción</th>
                 <th>Integrador</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
</div>